### ISSUE TITLE
ERR_REQUIRE_ESMエラーが出る

### ISSUE THREAD

**Issue by oageo** [oageo/nuxtblog-miller#3]
https://github.com/Osumi-Akari/nuxtblog-miller/commit/3f4213bee86bd36d8af004a370ab8865e314fda6 のエラー記録を見てみると、膨大なエラーが吐き出されていることがわかるが、remark系のプラグインから`ERR_REQUIRE_ESM`というエラーが吐き出されていることはわかる（license系のエラーはmillerlicense.vue関連の未実装によるもの）。

```bash
20:54:36.106 | yarn run v1.22.4
20:54:36.144 | $ nuxt generate
20:54:37.328 |  
20:54:37.329 | ERROR  Error [ERR_REQUIRE_ESM]: require() of ES Module /opt/buildhome/repo/node_modules/remark-external-links/index.js from /opt/buildhome/repo/node_modules/@nuxt/content/lib/utils.js not supported.
20:54:37.329 | Instead change the require of index.js in /opt/buildhome/repo/node_modules/@nuxt/content/lib/utils.js to a dynamic import() which is available in all CommonJS modules.
20:54:37.329 |  
20:54:37.367 |  
20:54:37.367 | ERROR  Error [ERR_REQUIRE_ESM]: require() of ES Module /opt/buildhome/repo/node_modules/remark-math/index.js from /opt/buildhome/repo/node_modules/@nuxt/content/lib/utils.js not supported.
20:54:37.367 | Instead change the require of index.js in /opt/buildhome/repo/node_modules/@nuxt/content/lib/utils.js to a dynamic import() which is available in all CommonJS modules.
20:54:37.368 |  
20:54:37.432 |  
20:54:37.433 | ERROR  Error [ERR_REQUIRE_ESM]: require() of ES Module /opt/buildhome/repo/node_modules/rehype-mathjax/index.js from /opt/buildhome/repo/node_modules/@nuxt/content/lib/utils.js not supported.
20:54:37.433 | Instead change the require of index.js in /opt/buildhome/repo/node_modules/@nuxt/content/lib/utils.js to a dynamic import() which is available in all CommonJS modules.
20:54:37.433 |  
20:54:40.156 |  
20:54:40.156 | ERROR  require() of ES Module /opt/buildhome/repo/node_modules/imagemin-mozjpeg/index.js from /opt/buildhome/repo/node_modules/@aceforth/nuxt-optimized-images/lib/loaders/img-loader.js not supported.
20:54:40.156 | Instead change the require of index.js in /opt/buildhome/repo/node_modules/@aceforth/nuxt-optimized-images/lib/loaders/img-loader.js to a dynamic import() which is available in all CommonJS modules.
20:54:40.157 |  
20:54:40.157 | Instead change the require of index.js in node_modules/@aceforth/nuxt-optimized-images/lib/loaders/img-loader.js to a dynamic import() which is available in all CommonJS modules.
20:54:40.157 | at requireImageminPlugin (node_modules/@aceforth/nuxt-optimized-images/lib/loaders/img-loader.js:20:10)
20:54:40.157 | at getImgLoaderOptions (node_modules/@aceforth/nuxt-optimized-images/lib/loaders/img-loader.js:41:11)
20:54:40.157 | at applyImgLoader (node_modules/@aceforth/nuxt-optimized-images/lib/loaders/img-loader.js:93:28)
20:54:40.157 | at appendLoaders (node_modules/@aceforth/nuxt-optimized-images/lib/loaders/index.js:134:14)
20:54:40.157 | at WebpackBundler.<anonymous> (node_modules/@aceforth/nuxt-optimized-images/lib/index.js:62:16)
20:54:40.157 | at WebpackBundler.<anonymous> (node_modules/@nuxt/utils/dist/utils.js:668:29)
20:54:40.158 | at WebpackClientConfig.extendConfig (node_modules/@nuxt/webpack/dist/webpack.js:1509:37)
20:54:40.158 | at WebpackClientConfig.config (node_modules/@nuxt/webpack/dist/webpack.js:1544:50)
20:54:40.158 | at WebpackClientConfig.config (node_modules/@nuxt/webpack/dist/webpack.js:1708:26)
20:54:40.158 | at WebpackBundler.getWebpackConfig (node_modules/@nuxt/webpack/dist/webpack.js:2016:19)
20:54:40.158 | at WebpackBundler.build (node_modules/@nuxt/webpack/dist/webpack.js:2023:12)
20:54:40.158 | at Builder.build (node_modules/@nuxt/builder/dist/builder.js:327:30)
20:54:40.158 | at async ensureBuild (node_modules/@nuxt/cli/dist/cli-generate.js:145:3)
20:54:40.158 | at async Object.run (node_modules/@nuxt/cli/dist/cli-generate.js:283:7)
20:54:40.158 | at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-index.js:413:7)
20:54:40.159 |  
20:54:40.230 |  
20:54:40.230 | ERROR  require() of ES Module /opt/buildhome/repo/node_modules/imagemin-mozjpeg/index.js from /opt/buildhome/repo/node_modules/@aceforth/nuxt-optimized-images/lib/loaders/img-loader.js not supported.
20:54:40.230 | Instead change the require of index.js in /opt/buildhome/repo/node_modules/@aceforth/nuxt-optimized-images/lib/loaders/img-loader.js to a dynamic import() which is available in all CommonJS modules.
20:54:40.231 |  
20:54:40.231 | Instead change the require of index.js in node_modules/@aceforth/nuxt-optimized-images/lib/loaders/img-loader.js to a dynamic import() which is available in all CommonJS modules.
20:54:40.231 | at requireImageminPlugin (node_modules/@aceforth/nuxt-optimized-images/lib/loaders/img-loader.js:20:10)
20:54:40.231 | at getImgLoaderOptions (node_modules/@aceforth/nuxt-optimized-images/lib/loaders/img-loader.js:41:11)
20:54:40.231 | at applyImgLoader (node_modules/@aceforth/nuxt-optimized-images/lib/loaders/img-loader.js:93:28)
20:54:40.231 | at appendLoaders (node_modules/@aceforth/nuxt-optimized-images/lib/loaders/index.js:134:14)
20:54:40.231 | at WebpackBundler.<anonymous> (node_modules/@aceforth/nuxt-optimized-images/lib/index.js:62:16)
20:54:40.232 | at WebpackBundler.<anonymous> (node_modules/@nuxt/utils/dist/utils.js:668:29)
20:54:40.232 | at WebpackServerConfig.extendConfig (node_modules/@nuxt/webpack/dist/webpack.js:1509:37)
20:54:40.232 | at WebpackServerConfig.config (node_modules/@nuxt/webpack/dist/webpack.js:1544:50)
20:54:40.232 | at WebpackServerConfig.config (node_modules/@nuxt/webpack/dist/webpack.js:1941:26)
20:54:40.232 | at WebpackBundler.getWebpackConfig (node_modules/@nuxt/webpack/dist/webpack.js:2016:19)
20:54:40.232 | at WebpackBundler.build (node_modules/@nuxt/webpack/dist/webpack.js:2031:32)
20:54:40.232 | at Builder.build (node_modules/@nuxt/builder/dist/builder.js:327:30)
20:54:40.232 | at async ensureBuild (node_modules/@nuxt/cli/dist/cli-generate.js:145:3)
20:54:40.233 | at async Object.run (node_modules/@nuxt/cli/dist/cli-generate.js:283:7)
20:54:40.233 | at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-index.js:413:7)
20:54:40.233 |  
20:54:56.684 |  
20:54:56.685 | ERROR  Error [ERR_REQUIRE_ESM]: require() of ES Module /opt/buildhome/repo/node_modules/remark-external-links/index.js from /opt/buildhome/repo/node_modules/@nuxt/content/lib/utils.js not supported.
20:54:56.685 | Instead change the require of index.js in /opt/buildhome/repo/node_modules/@nuxt/content/lib/utils.js to a dynamic import() which is available in all CommonJS modules.
20:54:56.685 |  
20:54:56.688 |  
20:54:56.688 | ERROR  Error [ERR_REQUIRE_ESM]: require() of ES Module /opt/buildhome/repo/node_modules/remark-math/index.js from /opt/buildhome/repo/node_modules/@nuxt/content/lib/utils.js not supported.
20:54:56.688 | Instead change the require of index.js in /opt/buildhome/repo/node_modules/@nuxt/content/lib/utils.js to a dynamic import() which is available in all CommonJS modules.
20:54:56.688 |  
20:54:56.691 |  
20:54:56.691 | ERROR  Error [ERR_REQUIRE_ESM]: require() of ES Module /opt/buildhome/repo/node_modules/rehype-mathjax/index.js from /opt/buildhome/repo/node_modules/@nuxt/content/lib/utils.js not supported.
20:54:56.691 | Instead change the require of index.js in /opt/buildhome/repo/node_modules/@nuxt/content/lib/utils.js to a dynamic import() which is available in all CommonJS modules.
20:54:56.692 |  
20:54:56.968 |  
20:54:56.968 | ERROR   /articles/test3
20:54:56.968 |  
20:54:56.968 | ReferenceError: license is not defined
20:54:56.968 | at a.data (pages/articles/_slug.vue:79:0)
20:54:56.968 | at a.Component.options.data (node_modules/.cache/nuxt/utils.js:82:0)
20:54:56.969 | at /opt/buildhome/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:28756
20:54:56.969 | at /opt/buildhome/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:28816
20:54:56.969 | at pn (/opt/buildhome/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:29023)
20:54:56.969 | at a.e._init (/opt/buildhome/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:32773)
20:54:56.969 | at new a (/opt/buildhome/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:30429)
20:54:56.969 | at Wi (/opt/buildhome/repo/node_modules/vue-server-renderer/build.prod.js:1:66558)
20:54:56.969 | at oo (/opt/buildhome/repo/node_modules/vue-server-renderer/build.prod.js:1:70788)
20:54:56.970 | at no (/opt/buildhome/repo/node_modules/vue-server-renderer/build.prod.js:1:70461)
20:54:56.970 | at to (/opt/buildhome/repo/node_modules/vue-server-renderer/build.prod.js:1:67708)
20:54:56.970 | at /opt/buildhome/repo/node_modules/vue-server-renderer/build.prod.js:1:70928
20:54:56.970 | at eo (/opt/buildhome/repo/node_modules/vue-server-renderer/build.prod.js:1:67418)
20:54:56.970 | at oo (/opt/buildhome/repo/node_modules/vue-server-renderer/build.prod.js:1:70830)
20:54:56.970 | at no (/opt/buildhome/repo/node_modules/vue-server-renderer/build.prod.js:1:70461)
20:54:56.971 | at to (/opt/buildhome/repo/node_modules/vue-server-renderer/build.prod.js:1:67708)
20:54:56.971 |  
20:54:56.972 |  
20:54:56.972 | ERROR   /articles/test2
20:54:56.972 |  
20:54:56.972 | ReferenceError: license is not defined
20:54:56.973 | at a.data (pages/articles/_slug.vue:79:0)
20:54:56.973 | at a.Component.options.data (node_modules/.cache/nuxt/utils.js:82:0)
20:54:56.973 | at /opt/buildhome/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:28756
20:54:56.973 | at /opt/buildhome/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:28816
20:54:56.973 | at pn (/opt/buildhome/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:29023)
20:54:56.973 | at a.e._init (/opt/buildhome/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:32773)
20:54:56.973 | at new a (/opt/buildhome/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:30429)
20:54:56.973 | at Wi (/opt/buildhome/repo/node_modules/vue-server-renderer/build.prod.js:1:66558)
20:54:56.973 | at oo (/opt/buildhome/repo/node_modules/vue-server-renderer/build.prod.js:1:70788)
20:54:56.974 | at no (/opt/buildhome/repo/node_modules/vue-server-renderer/build.prod.js:1:70461)
20:54:56.974 | at to (/opt/buildhome/repo/node_modules/vue-server-renderer/build.prod.js:1:67708)
20:54:56.974 | at /opt/buildhome/repo/node_modules/vue-server-renderer/build.prod.js:1:70928
20:54:56.974 | at eo (/opt/buildhome/repo/node_modules/vue-server-renderer/build.prod.js:1:67418)
20:54:56.974 | at oo (/opt/buildhome/repo/node_modules/vue-server-renderer/build.prod.js:1:70830)
20:54:56.974 | at no (/opt/buildhome/repo/node_modules/vue-server-renderer/build.prod.js:1:70461)
20:54:56.974 | at to (/opt/buildhome/repo/node_modules/vue-server-renderer/build.prod.js:1:67708)
20:54:56.974 |  
20:54:56.976 |  
20:54:56.976 | ERROR   /articles/test
20:54:56.976 |  
20:54:56.976 | ReferenceError: license is not defined
20:54:56.977 | at a.data (pages/articles/_slug.vue:79:0)
20:54:56.977 | at a.Component.options.data (node_modules/.cache/nuxt/utils.js:82:0)
20:54:56.977 | at /opt/buildhome/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:28756
20:54:56.977 | at /opt/buildhome/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:28816
20:54:56.977 | at pn (/opt/buildhome/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:29023)
20:54:56.977 | at a.e._init (/opt/buildhome/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:32773)
20:54:56.977 | at new a (/opt/buildhome/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:30429)
20:54:56.977 | at Wi (/opt/buildhome/repo/node_modules/vue-server-renderer/build.prod.js:1:66558)
20:54:56.977 | at oo (/opt/buildhome/repo/node_modules/vue-server-renderer/build.prod.js:1:70788)
20:54:56.978 | at no (/opt/buildhome/repo/node_modules/vue-server-renderer/build.prod.js:1:70461)
20:54:56.978 | at to (/opt/buildhome/repo/node_modules/vue-server-renderer/build.prod.js:1:67708)
20:54:56.978 | at /opt/buildhome/repo/node_modules/vue-server-renderer/build.prod.js:1:70928
20:54:56.978 | at eo (/opt/buildhome/repo/node_modules/vue-server-renderer/build.prod.js:1:67418)
20:54:56.978 | at oo (/opt/buildhome/repo/node_modules/vue-server-renderer/build.prod.js:1:70830)
20:54:56.978 | at no (/opt/buildhome/repo/node_modules/vue-server-renderer/build.prod.js:1:70461)
20:54:56.978 | at to (/opt/buildhome/repo/node_modules/vue-server-renderer/build.prod.js:1:67708)
20:54:56.979 |  
20:54:56.980 |  
20:54:56.980 | ERROR   /articles/example1
20:54:56.980 |  
20:54:56.981 | ReferenceError: license is not defined
20:54:56.981 | at a.data (pages/articles/_slug.vue:79:0)
20:54:56.981 | at a.Component.options.data (node_modules/.cache/nuxt/utils.js:82:0)
20:54:56.981 | at /opt/buildhome/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:28756
20:54:56.981 | at /opt/buildhome/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:28816
20:54:56.981 | at pn (/opt/buildhome/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:29023)
20:54:56.982 | at a.e._init (/opt/buildhome/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:32773)
20:54:56.982 | at new a (/opt/buildhome/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:30429)
20:54:56.982 | at Wi (/opt/buildhome/repo/node_modules/vue-server-renderer/build.prod.js:1:66558)
20:54:56.982 | at oo (/opt/buildhome/repo/node_modules/vue-server-renderer/build.prod.js:1:70788)
20:54:56.982 | at no (/opt/buildhome/repo/node_modules/vue-server-renderer/build.prod.js:1:70461)
20:54:56.982 | at to (/opt/buildhome/repo/node_modules/vue-server-renderer/build.prod.js:1:67708)
20:54:56.982 | at /opt/buildhome/repo/node_modules/vue-server-renderer/build.prod.js:1:70928
20:54:56.982 | at eo (/opt/buildhome/repo/node_modules/vue-server-renderer/build.prod.js:1:67418)
20:54:56.982 | at oo (/opt/buildhome/repo/node_modules/vue-server-renderer/build.prod.js:1:70830)
20:54:56.982 | at no (/opt/buildhome/repo/node_modules/vue-server-renderer/build.prod.js:1:70461)
20:54:56.983 | at to (/opt/buildhome/repo/node_modules/vue-server-renderer/build.prod.js:1:67708)
20:54:56.983 |  
20:54:57.641 | Done in 21.54s.
```

これに付随してMarkdownがnuxt/contentによって正しく処理されていないため早急に解決数r必要があると考える。

**Comment by oageo** [comment]
#16 によって解決されていそうなのでClose
